export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const FECTH_TASKS_REQEST = 'FECTH_TASKS_REQEST';
export const FECTH_TASKS_SUCCESS = 'FECTH_TASKS_SUCCESS';
export const FECTH_TASKS_FAILED = 'FECTH_TASKS_FAILED';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_FIELD = 'CHANGE_FIELD';
